# Generated by Django 3.2.8 on 2021-10-23 15:06

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('AIRING', 'Currently Aring'), ('FINISHED', 'Finished Airing')], max_length=255, verbose_name='current status of anime'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('TV', 'TV'), ('MOVIE', 'Movie')], max_length=255, verbose_name='where did the anime air'),
        ),
    ]
