# Generated by Django 3.2.8 on 2021-10-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211028_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
